import 'bootstrap/dist/css/bootstrap.min.css'
import { Inter } from 'next/font/google'
import './globals.css'
import styles from './page.module.css'
import TopBar from "./components/TopBar/TopBar"

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <title>Nicolas</title>
      <body className={`${inter.className} container-fluid ${styles.main}`}>
        <TopBar />
        {children}
      </body>
    </html>
  )
}
